### ISSUE TITLE
AttributeError: module 'enum' has no attribute 'StrEnum'

### ISSUE THREAD

**Issue by AlessandroMiola** [talkpython/audio-ai-with-assemblyai-course#1]
Hi Micheal, 
thank you for the great course and for your amazing work!
While following along the course, I got into the following issue

    class JobStatus(enum.StrEnum):
    AttributeError: module 'enum' has no attribute 'StrEnum'

If I didn't get it wrong, `StrEnum` should be compatible with version `>=3.11`, which causes problems when run with a version in `[3.9, 3.11)`.

Inheriting from `enum.Enum` just works, but I'm just at the beginning of the course and I don't know whether this might trigger unintended behaviour :)

**Comment by mikeckennedy** [comment]
Hey @AlessandroMiola Python versioning strikes again! `StrEnum` was added to Python in 3.11 and I thought it was there earlier as you point out. 

While `enum.Enum` works at the start, it fails later. I added the package from PyPI StrEnum and swapped that out. It's all good now. See 1c008bc57f406cbb61b37ffb87b206089655099d for details.

Thank you for taking the time to report this.
